import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from './theme-provider';

const inter = Inter({ subsets: ["latin"] });

// a common layout and design will goes here

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProviderWrapper>
      <body className={inter.className}>{children}</body>
      </ThemeProviderWrapper>
     
    </html>
  );
}
